### ISSUE TITLE
error: API request failed   caused by: sentry reported an error: unknown error (http status: 413)

### ISSUE THREAD

**Issue by PeOS-China** [getsentry/sentry-android-gradle-plugin#494]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.0.1

### Proguard

Enabled

### Version

6.8.0

### Steps to Reproduce

When compiling the Android project, an exception is reported during the stage of uploading the Map file of sentry.
The Map file is very big: 182M

### Expected Result
Log：
`

> Task :app:uploadSentryProguardMappingsRelease
  INFO    2023-05-23 17:03:36.592623 +08:00 Loaded file referenced by SENTRY_PROPERTIES (/Users/admin/Downloads/AndroidCode/DM/barbell/app/sentry.properties)
> compressing mappings
> uploading mappings
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
API request failed
<img width="768" alt="image" src="https://github.com/getsentry/sentry-java/assets/8873336/ba1a233f-d0dc-4ec0-882a-ea5e2106d158">

`

### Actual Result
`

> Task :app:uploadSentryProguardMappingsRelease
  INFO    2023-05-23 17:03:36.592623 +08:00 Loaded file referenced by SENTRY_PROPERTIES (/Users/admin/Downloads/AndroidCode/DM/barbell/app/sentry.properties)
> compressing mappings
> uploading mappings
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
API request failed
<img width="768" alt="image" src="https://github.com/getsentry/sentry-java/assets/8873336/ba1a233f-d0dc-4ec0-882a-ea5e2106d158">

`

**Comment by PaulWoitaschek** [comment]
This isn't a question but a bug. With the full mode which is enabled by default from AGP 8 on, this will quickly affect any app that has a certain size.

**Comment by romtsn** [comment]
@PaulWoitaschek are you having the same issue?

**Comment by PaulWoitaschek** [comment]
Yes, exactly the same.

**Comment by romtsn** [comment]
> Yes, exactly the same.

Can I know your mapping file size? Also, any reason you have not reported that earlier, or you've got a workaround?

**Comment by adrianolc** [comment]
@romtsn, I work with @PaulWoitaschek and this is the size of our mapping files. We start to get this error today after enable the full mode from R8

![Screenshot 2023-05-23 at 12 39 58](https://github.com/getsentry/sentry-android-gradle-plugin/assets/4654098/ee7e31cd-f7b7-47b6-8c1d-da8dc3fd0081)

**Comment by romtsn** [comment]
@adrianolc @PaulWoitaschek thank you! It looks like you got hit by an incident we've had today coincidentally https://status.sentry.io/incidents/mdblw8vxzpl0

May you try to upload the files again? I'm still awaiting the response from our Ops team, but it looks like it got resolved already.

**Comment by romtsn** [comment]
@adrianolc @PaulWoitaschek @PeOS-China I'm gonna close this as the incident has been resolved, feel free to reopen/comment if that's still the case for you. Thank you and apologies for the inconvenience!

**Comment by PaulWoitaschek** [comment]
Thanks for the quick response. We will check with the next release and report back in case it's still broken.

**Comment by romtsn** [comment]
@CurtJRees thanks for letting us know. Is it still happening for you or this was a one-time thing? If it still is, could you enable debug logging of the plugin (it's available in the latest version 3.10.0)
```gradle.kts
sentry {
  debug.set(true) // debug = true for .gradle
}
```
and share the output with us? Thanks!

**Comment by CurtJRees** [comment]
It's still happening for me, although I've since tried the CLI and I'm getting the same error from there
So it may be unrelated to the gradle plugin itself

I'll grab the debug logs now, but will have to hide some details we're self hosting sentry and can't share too many details on the project

**Comment by CurtJRees** [comment]
Here's the debug logs:

```
> Task :app:uploadSentryProguardMappingsProdRelease FAILED
  INFO    2023-06-13 15:31:04.580619 +01:00 Loaded file referenced by SENTRY_PROPERTIES (/Users/curt/Android/PROJECT_SLUG/sentry.properties)
  INFO    2023-06-13 15:31:04.582574 +01:00 Loaded config from /Users/curt/.sentryclirc
  DEBUG   2023-06-13 15:31:04.582584 +01:00 sentry-cli version: 2.18.1, platform: "darwin", architecture: "arm64"
  INFO    2023-06-13 15:31:04.582621 +01:00 sentry-cli was invoked with the following command line: "/var/folders/hs/r2dv4p8x499__9smkjh7j90r0000gp/T/.sentry-cli16166226498802790888.exe" "--log-level=debug" "upload-proguard" "--uuid" "3548f839-dd07-4999-ab8b-863147d7af4d" "/Users/curt/Android/PROJECT_SLUG/app/build/outputs/mapping/prodRelease/mapping.txt"
  DEBUG   2023-06-13 15:31:04.637278 +01:00 SHA1 for mapping file '/Users/curt/Android/PROJECT_SLUG/app/build/outputs/mapping/prodRelease/mapping.txt': '4ff993afa51fc2db9dc5c15ac87d8167392bd57c'
> compressing mappings
  INFO    2023-06-13 15:31:04.972904 +01:00 Issuing a command for Organization: SELF_HOSTED_ORG Project: PROJECT_SLUG
> uploading mappings
  DEBUG   2023-06-13 15:31:04.972992 +01:00 request POST https://SELF_HOSTED_URL/api/0/projects/SELF_HOSTED_ORG/PROJECT_SLUG/files/dsyms/
  DEBUG   2023-06-13 15:31:04.973 +01:00 using token authentication
  DEBUG   2023-06-13 15:31:04.973013 +01:00 sending form data
  DEBUG   2023-06-13 15:31:04.973015 +01:00 retry number 0, max retries: 0
  DEBUG   2023-06-13 15:31:05.064284 +01:00 > POST /api/0/projects/SELF_HOSTED_ORG/PROJECT_SLUG/files/dsyms/ HTTP/1.1
  DEBUG   2023-06-13 15:31:05.064295 +01:00 > Host: SELF_HOSTED_URL
  DEBUG   2023-06-13 15:31:05.064298 +01:00 > Accept: */*
  DEBUG   2023-06-13 15:31:05.064300 +01:00 > Connection: TE
  DEBUG   2023-06-13 15:31:05.064302 +01:00 > TE: gzip
  DEBUG   2023-06-13 15:31:05.064308 +01:00 > User-Agent: sentry-cli/2.18.1
  DEBUG   2023-06-13 15:31:05.064542 +01:00 > Authorization: Bearer fe00d107***
  DEBUG   2023-06-13 15:31:05.064545 +01:00 > Content-Length: 2450242
  DEBUG   2023-06-13 15:31:05.064547 +01:00 > Content-Type: multipart/form-data; boundary=------------------------2e4b0b15935eb347
  DEBUG   2023-06-13 15:31:05.085773 +01:00 response status: 413
  DEBUG   2023-06-13 15:31:05.085779 +01:00 body: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)
  DEBUG   2023-06-13 15:31:05.086003 +01:00 skipping update nagger because session is not attended
```

**Comment by romtsn** [comment]
@CurtJRees but if you're using self-hosted this is most likely an issue in your setup (perhaps not enough storage space?). Or has this issue started to appear after you'd updated your self-hosted version?
